import pymc as pm
import numpy as np
import arviz as az
import matplotlib.pyplot as plt

# --- 1. The Data ---
# Let's imagine we have the fantasy scores for a wide receiver over 16 weeks.
# This player is a bit volatile.
player_scores = np.array([
    12.5, 28.3, 8.1, 15.7, 3.2, 22.1, 14.8, 16.2, 
    5.5, 33.0, 11.4, 9.8, 19.5, 25.1, 7.9, 13.4
])

print(f"Observed scores for the player: \n{player_scores}")
print(f"Average score (simple mean): {player_scores.mean():.2f}\n")


# --- 2. Build the Bayesian Model with PyMC ---
# We define our model within a "with pm.Model()" block.

with pm.Model() as player_model:
    # --- Priors ---
    # These are our initial beliefs about the player before seeing the data.
    # We choose "weakly informative" priors that are reasonable but let the data speak for itself.

    # Prior for μ (the player's "true talent" average score)
    # We'll model it as a Normal distribution. Let's assume an average WR scores around 15 points,
    # with a standard deviation of 5. This is a reasonable starting guess.
    mu = pm.Normal("mu", mu=15, sigma=5)

    # Prior for σ (the player's week-to-week volatility/standard deviation)
    # Standard deviation must be positive, so we use a HalfNormal distribution.
    # A sigma of 10 means most scores fall within a 20-point range of the mean, which is plausible.
    sigma = pm.HalfNormal("sigma", sigma=10)

    # --- Likelihood ---
    # This is the engine of the model. It connects our parameters (mu and sigma) to the actual data.
    # We are saying that our observed 'player_scores' are drawn from a Normal distribution
    # defined by the 'mu' and 'sigma' we are trying to estimate.
    y_observed = pm.Normal("y_observed", mu=mu, sigma=sigma, observed=player_scores)


# --- 3. Run the MCMC Sampler ---
# This is where the magic happens. PyMC will use a powerful MCMC algorithm (NUTS sampler)
# to explore the parameter space and find the most plausible values for 'mu' and 'sigma'.
# We are drawing 2000 samples from the "posterior" distribution.
with player_model:
    # The MCMC sampler runs here
    trace = pm.sample(2000, tune=1000, cores=1)


# --- 4. Analyze the Results and Predict for Next Week ---
# The 'trace' object contains all the samples generated by the MCMC process.
# Each sample is a plausible guess for our parameters given the data.

# ArviZ gives us a nice summary of the posterior distributions for our parameters.
print("\n--- Model Results ---")
print(az.summary(trace, round_to=2))

# To predict the score for next week (Week 17), we don't need to do anything complex.
# The posterior distribution for 'mu' IS our prediction. It represents the range of
# likely "true averages" for the player. Any score generated from these parameters
# is a plausible outcome for next week.
# We can simulate next week's scores by drawing from a Normal distribution using
# each of our posterior samples for mu and sigma.
posterior_mu = trace.posterior['mu'].values.flatten()
posterior_sigma = trace.posterior['sigma'].values.flatten()

# Generate 10,000 possible scores for next week based on our model
next_week_prediction_dist = np.random.normal(loc=posterior_mu, scale=posterior_sigma)


# --- 5. Visualize the Prediction ---
plt.style.use("arviz-themes.arviz-darkgrid")
fig, ax = plt.subplots(figsize=(10, 6))

# Plot the distribution of possible scores for next week
az.plot_kde(next_week_prediction_dist, ax=ax)

# Calculate and display key statistics
mean_pred = next_week_prediction_dist.mean()
median_pred = np.median(next_week_prediction_dist)
ci_95 = np.percentile(next_week_prediction_dist, [2.5, 97.5])

ax.set_title(f"Predicted Score Distribution for Next Week", fontsize=16)
ax.set_xlabel("Fantasy Points", fontsize=12)
ax.set_ylabel("Probability Density", fontsize=12)
ax.axvline(mean_pred, color='red', linestyle='--', label=f'Mean Projection: {mean_pred:.2f}')
ax.axvspan(ci_95[0], ci_95[1], color='red', alpha=0.1, label=f'95% Credible Interval: [{ci_95[0]:.2f}, {ci_95[1]:.2f}]')

plt.legend()
plt.show()

print("\n--- Prediction Summary ---")
print(f"The model predicts the player's score next week will be, on average, {mean_pred:.2f} points.")
print(f"There is a 95% probability that the player's score will fall between {ci_95[0]:.2f} and {ci_95[1]:.2f} points.")
